import json
import os

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """Assess whether a piece of text was written by a human or generated by an AI language model.

Judge based on tone, idiom, and stylistic naturalness. Signs of AI generation include uniform hedging ("it is important to note", "on the other hand"), generic phrasing, and an overly balanced, non-committal structure. Signs of human authorship include a distinctive voice, specific idiosyncratic detail, and irregular phrasing.

Respond with ONLY a JSON object in this exact format, no other text:
{"ai_score": <float between 0.0 and 1.0, where 1.0 means confidently AI-generated and 0.0 means confidently human-written>, "rationale": "<one sentence explaining the score>"}
"""

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def get_llm_score(text):
    """Groq LLM classification. Returns {"ai_score": float, "rationale": str}."""
    client = _get_client()
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )
    result = json.loads(completion.choices[0].message.content)
    return {
        "ai_score": float(result["ai_score"]),
        "rationale": result.get("rationale", ""),
    }
