import json
import os
import re

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """Assess whether a piece of text was written by a human or generated by an AI language model.

Judge based on tone, idiom, and stylistic naturalness. Signs of AI generation include generic phrasing and an overly balanced, non-committal structure. Signs of human authorship include a distinctive voice, specific idiosyncratic detail, and irregular phrasing.

Respond with ONLY a JSON object in this exact format, no other text:
{"ai_score": <float between 0.0 and 1.0, where 1.0 means confidently AI-generated and 0.0 means confidently human-written>, "rationale": "<one sentence explaining the score>"}
"""

# Commonly-cited connector/hedge phrases associated with LLM output (not
# exhaustive — a text avoiding this exact vocabulary will evade this metric).
# Kept out of SYSTEM_PROMPT above so Signal 1 judges tone/voice holistically
# rather than duplicating this mechanical phrase count.
CONNECTOR_PHRASES = [
    "it is important to note", "it is worth noting", "it is essential to", "it is crucial to",
    "on the other hand", "furthermore", "moreover", "additionally", "in conclusion", "in summary",
    "that being said", "with that said", "as such", "plays a crucial role", "plays a vital role",
    "delve into", "in today's fast-paced world", "underscore", "seamless", "robust", "leverage", "navigate",
]

_client = None


def _get_client():
    # Lazy singleton: avoids reading GROQ_API_KEY at import time, so importing
    # this module doesn't fail before .env has been loaded by the caller.
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def get_llm_score(text):
    """Groq LLM classification. Returns {"ai_score": float, "rationale": str}."""
    client = _get_client()
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )
    result = json.loads(completion.choices[0].message.content)
    return {
        "ai_score": float(result["ai_score"]),
        "rationale": result.get("rationale", ""),
    }


def _split_sentences(text):
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s for s in sentences if s]


def _words(text):
    return re.findall(r"[A-Za-z']+", text.lower())


def get_style_score(text):
    """Stylometric heuristics. Returns {"style_score": float, "sub_scores": {...}}.

    Combines three sub-metrics, each normalized to [0, 1] "AI-likeness" and
    averaged: sentence length variance, punctuation density, and
    connector-phrase density. Type-token ratio was dropped after calibration
    testing showed it stayed flat (0.10-0.14) regardless of authorship across
    all four calibration texts. See planning.md section 1 for the
    normalization constants and reasoning behind each.
    """
    sentences = _split_sentences(text)
    words = _words(text)

    sentence_lengths = [len(_words(s)) for s in sentences]
    if len(sentence_lengths) >= 2:
        mean_len = sum(sentence_lengths) / len(sentence_lengths)
        variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    else:
        variance = 0.0

    punct_count = text.count(",") + text.count(";") + text.count(":")
    commas_per_sentence = punct_count / len(sentences) if sentences else 0.0

    lower_text = text.lower()
    connector_count = sum(lower_text.count(phrase) for phrase in CONNECTOR_PHRASES)
    connectors_per_100_words = connector_count / len(words) * 100 if words else 0.0

    variance_subscore = 1 - min(variance, 40) / 40
    punct_subscore = min(commas_per_sentence, 3) / 3
    connector_subscore = min(connectors_per_100_words, 3) / 3

    style_score = (variance_subscore + punct_subscore + connector_subscore) / 3

    return {
        "style_score": style_score,
        "sub_scores": {
            "sentence_length_variance": variance,
            "commas_per_sentence": commas_per_sentence,
            "connectors_per_100_words": connectors_per_100_words,
            "variance_subscore": variance_subscore,
            "punct_subscore": punct_subscore,
            "connector_subscore": connector_subscore,
        },
    }
